use_frameworks!

workspace '../FlexLayout.xcworkspace'

target 'FlexLayoutSample' do
  project 'FlexLayoutSample.xcodeproj'

  pod 'FlexLayoutTest', :path => '../'
  pod 'PinLayout'

  # Debug only
  pod 'Reveal-SDK', :configurations => ['Debug']
  pod 'SwiftLint'
end
