engines:
  tailor:
    enabled: true

ratings:
  paths:
  - "**.swift"

exclude_paths:
    - FlexLayoutTests
    - Pods_FlexLayout
    - Pods_FlexLayoutTests
    - Example
    - Pods
    - data
    - docs
    