source 'https://cdn.cocoapods.org/'
use_frameworks!
platform :ios, '12.0'

workspace 'FlexLayoutSample.xcworkspace'

target 'FlexLayoutSample' do
  project 'FlexLayoutSample.xcodeproj'

  pod 'FlexLayout', path: '../..'
  pod 'PinLayout'

  # Debug only
  pod 'SwiftLint'
end
